import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes.js';
import escritorioRoutes from './modules/escritorio/escritorio.routes.js';
import usuarioRoutes from './modules/usuario/usuario.routes.js';
import departamentoRoutes from './modules/departamento/departamento.routes.js';
import tagRoutes from './modules/tag/tag.routes.js';
import empresaRoutes from './modules/empresa/empresa.routes.js';
import insightsRoutes from './modules/insights/insights.routes.js';
import obrigacaoRoutes from './modules/obrigacao/obrigacao.routes.js';
import regimeRoutes from './modules/obrigacao/regime.routes.js';
import grupoRoutes from './modules/obrigacao/grupo.routes.js';
import feriadoRoutes from './modules/obrigacao/feriado.routes.js';
import empresaObrigacaoRoutes from './modules/obrigacao/empresaObrigacao.routes.js';
import entregaRoutes from './modules/entrega/entrega.routes.js';
import auditoriaRoutes from './modules/auditoria/auditoria.routes.js';
import gedRoutes from './modules/ged/ged.routes.js';
import protocoloRoutes from './modules/protocolo/protocolo.routes.js';
import protocoloFisicoRoutes from './modules/protocolo/protocoloFisico.routes.js';
import roboRoutes from './modules/robo/robo.routes.js';
import assinaturaRoutes from './modules/robo/assinatura.routes.js';
import matrizRoutes from './modules/processo/matriz.routes.js';
import processoRoutes from './modules/processo/processo.routes.js';
import portalRoutes from './modules/portal/portal.routes.js';
import gestaoPortalRoutes from './modules/portal/gestao.routes.js';
import comunicacaoRoutes from './modules/comunicacao/comunicacao.routes.js';
import solicitacaoInternaRoutes from './modules/solicitacaoInterna/solicitacaoInterna.routes.js';
import notificacaoRoutes from './modules/jobs/notificacao.routes.js';
import aplaRoutes from './modules/apla/apla.routes.js';

const api = Router();

api.get('/health', (_req, res) => {
  res.json({ ok: true, data: { status: 'up', ts: new Date().toISOString() } });
});

api.use('/auth', authRoutes);
api.use('/escritorio', escritorioRoutes);
api.use('/usuarios', usuarioRoutes);
api.use('/departamentos', departamentoRoutes);
api.use('/tags', tagRoutes);
api.use('/empresas', empresaRoutes);
api.use('/insights', insightsRoutes);
api.use('/obrigacoes', obrigacaoRoutes);
api.use('/regimes', regimeRoutes);
api.use('/grupos', grupoRoutes);
api.use('/feriados', feriadoRoutes);
api.use('/empresa-obrigacoes', empresaObrigacaoRoutes);
api.use('/entregas', entregaRoutes);
api.use('/auditoria', auditoriaRoutes);
api.use('/ged', gedRoutes);
api.use('/protocolos', protocoloRoutes);
api.use('/protocolos-fisicos', protocoloFisicoRoutes);
api.use('/robo', roboRoutes);
api.use('/assinaturas', assinaturaRoutes);
api.use('/matrizes', matrizRoutes);
api.use('/processos', processoRoutes);
api.use('/portal', portalRoutes);
api.use('/gestao-portal', gestaoPortalRoutes);
api.use('/comunicacao', comunicacaoRoutes);
api.use('/solicitacoes-internas', solicitacaoInternaRoutes);
api.use('/notificacoes', notificacaoRoutes);
api.use('/apla', aplaRoutes);

export default api;
